---
# This playbook deploys the wemux role for testing

- hosts: test-kitchen
  user: root
  pre_tasks:
    - include_vars: "vars/vault-example.yml"
    - name: Output the encrypted var
      debug: var=my_var

  roles:
    - ansible-role-wemux
